//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBank_PBD.Models
{
    using System.ComponentModel.DataAnnotations;

    public partial class Test
    {
        [Key]
        [Display(Name = "Test ID")]
        public int TestId { get; set; }
        [Display(Name = "Donor's Name")]
        [MaxLength(50)]
        public string DonorFullName { get; set; }
        [Display(Name = "Weight (kg)")]
        [Required(ErrorMessage = "Weight cannot be blank")]
        public int Weight { get; set; }
        [Display(Name = "Height (cm)")]
        [Required(ErrorMessage = "Height cannot be blank")]
        public int Height { get; set; }
        [Required(ErrorMessage = "BP cannot be blank")]
        public int BP { get; set; }
        [MaxLength(9)]
        public string Progress { get; set; }
        [Required(ErrorMessage = "Make sure you enter a date.")]
        public System.DateTime Date { get; set; }
        public int UserId { get; set; }

        public virtual User User { get; set; }
    }
}
